services:
  db:
    image: postgres:16
    container_name: appdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d